version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "petclinic-rest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - DOCKER_LOGIN=`aws ecr get-login --no-include-email`
      - ${DOCKER_LOGIN}
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - mvn clean package docker:build -Dmaven.test.skip=true
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/$IMAGE_REPO_NAME:latest

cache:
  paths:
    - '/root/.m2/**/*'